### ISSUE TITLE
好评如潮配置简单，v2ray+trojan+web全部塞里面，了却haproxy配置连接不上的烦恼

### ISSUE THREAD

**Issue by ALfheimr-SAO** [liberal-boy/tls-shunt-proxy#1]

**Comment by bymao** [comment]
这个确实方便。。NGINX都不需要了。。

**Comment by wonpn** [comment]
纯静态网页确实方便，nginx放动态页面就不行了

**Comment by wonpn** [comment]
把纯http转发到nginx上其实也行。
多一层wss性能差别应该不大， 有空再折腾哇

**Comment by liberal-boy** [comment]
> 把纯http转发到nginx上其实也行。
> 多一层wss性能差别应该不大， 有空再折腾哇

ws 可以在分流器用 path 分流，不需要过 nginx

**Comment by wellsony** [comment]
> > 把纯http转发到nginx上其实也行。
> > 多一层wss性能转换应该不大，有空再折腾哇
> 
> ws可以在分流器用path分流，不需要过nginx
能把http重定向到https上吗

**Comment by PigodChen** [comment]
@liberal-boy  要不要考虑加个指定cipher的功能
