### ISSUE TITLE
support ecdsa certificates in managedcert

### ISSUE THREAD

**Issue by phlinhng** [liberal-boy/tls-shunt-proxy#13]
`go-acme/lego` 支持 ecdsa 證書申請，如果不麻煩的話，希望可以加上內建 ACME 模塊的 ecdsa 支持。

**Comment by liberal-boy** [comment]
现在不能使用ecdsa证书么？

**Comment by phlinhng** [comment]
自己配置是可以用的，但是通過內建的 ACME 模塊只能申請 RSA-2048 證書。`go-acme/lego`支持 ecdsa 證書申請，如果不麻煩的話，希望可以加上內建 ACME 模塊的 ecdsa 支持。

**Comment by phlinhng** [comment]
抱歉，我測錯站點了。分流器申請的證書是 ecdsa 沒錯，不好意思打擾到您。

**Comment by liberal-boy** [comment]
acme申请的证书的确是rsa2048的，会考虑支持选择密钥对类型。

**Comment by phlinhng** [comment]
我是用 ssllab 網站測的    
一開始測錯的網站（非TLS分流器搭建）顯示的證書是類型是 `RSA 2048 bits (SHA256withRSA)`    
後來測試了 TLS 分流器搭建的網站顯示的證書類型是 `EC 256 bits (SHA256withRSA)`，信任鏈是這樣 `mysite (EC 256 bits / SHA256withRSA)` -> `Let's Encrypt Authority X3 (RSA 2048 bits (e 65537) / SHA256withRSA)` -> `DST Root CA X3 (RSA 2048 bits (e 65537) / SHA256withRSA)`

**Comment by liberal-boy** [comment]
总之还是加个可选项比较好吧。

**Comment by phlinhng** [comment]
這是您的項目，由您決定吧。建議加了之後，默認證書類型還是像 caddy 一樣維持 ec-256。

**Comment by liberal-boy** [comment]
ff11b8f
