### ISSUE TITLE
只支持静态，可以反代其他端口的应用吗？

### ISSUE THREAD

**Issue by hqhyco** [liberal-boy/tls-shunt-proxy#17]
- name: trojan.example.com
    tlsoffloading: false
    default:
      handler: proxyPass
      args: 127.0.0.1:8080
我在8080端口搭了个网盘，是分流器不支持吗，提示failed to connect什么什么的

**Comment by liberal-boy** [comment]
请先检查8080端口的应用是否正常，已经发送到分流器的请求是否包含sni，本项目只是一个反向代理工具，只要是有sni的tls请求都支持。
