### ISSUE TITLE
请教让emby-server走443方式

### ISSUE THREAD

**Issue by ghost** [liberal-boy/tls-shunt-proxy#22]
你好，请教一下：
我现在用tls-shunt-proxy 分流伪装网站html和trojan
tls-shunt-proxy的config.json这样：
vhosts:
  - name: 867867.pw
    tlsoffloading: true
    managedcert: true
    keytype: p256
    alpn: h2,http/1.1
    protocols: tls12,tls13
    http:
      handler: fileServer
      args: /var/www/html
    trojan:
      handler: proxyPass
      args: 127.0.0.1:22567

vps还搭建了emyb-server，用8096默认端口正常观影

然后想让emby走443，替换掉html伪装网站

尝试args: /var/www/html改成args: 127.0.0.1:8096
访问https提示404 page not found；

然后卡住不知道怎么处理了~

特此上来求助下 :)

**Comment by h31105** [comment]
如果default分流没有占用的话，可以考虑用default分流试试

**Comment by liberal-boy** [comment]
@wsa01378 请发修改后的完整配置文件

**Comment by ghost** [comment]
@liberal-boy 你好，我改成这样，能用了。不知这样写正不正确

<details>
<summary>展开查看</summary>
<pre><code>

listen: 0.0.0.0:443
redirecthttps: 0.0.0.0:80

vhosts:

 name: domain.com
    tlsoffloading: true
    managedcert: true
    http:
      handler: proxyPass
      args: 127.0.0.1:8096
    trojan:
      handler: proxyPass
      args: 127.0.0.1:22567

</code></pre>
</details>

**Comment by tudoubocai** [comment]
> 如果default分流没有占用的话，可以考虑用default分流试试

求配置方法
    default:
      handler: proxyPass
      args: 127.0.0.1:8080 
这样，并注释掉fileserver，没法打开网页……

**Comment by tudoubocai** [comment]
看到你在别的发放发的帖子了，又在这里看到。虽然过了两年了。但我还是把我的解决方案贴在这里
用另一个域名。

在vhosts下面添加

- name: www.xxxx.com   "name前面明明是一个英文减号，为何提交后变成原点了"
tlsoffloading: true
managedcert: true
default:
handler: proxyPass
args: 127.0.0.1:8080
这样，trojan里面用tr.xxxx.com
两个域名都走443端口。完美解决！
