### ISSUE TITLE
tlsoffloading为false时    managedcert: true不签证书     

### ISSUE THREAD

**Issue by ghost** [liberal-boy/tls-shunt-proxy#25]
版本0.61
发现个问题，写成下面这样时，letsencrypt.org-directory里找不到 trojan.myname.com的证书，只找到v2.myname.com证书（DNS解析正确）。第一段vhost复制下去，域名改成trojan.myname.com则签出来了

listen: 0.0.0.0:443
inboundbuffersize: 4
outboundbuffersize: 32
vhosts:
  - name: v2.myname.com
    tlsoffloading: true
    managedcert: true
    alpn: h2,http/1.1
    protocols: tls12,tls13
    http:
      handler: fileServer
      args: /var/www/html
    default:
      handler: proxyPass
      args: 127.0.0.1:60001

  - name: trojan.myname.com
    managedcert: true
    tlsoffloading: false
    default:
      handler: proxyPass
      args: 127.0.0.1:60002

**Comment by liberal-boy** [comment]
分流器申请证书的目的是供 offloading 时使用，如关闭 offloading，当然不会申请证书。
