### ISSUE TITLE
sniff 后 http2 无法被反代

### ISSUE THREAD

**Issue by josh-chan** [liberal-boy/tls-shunt-proxy#28]
浏览器打开直接就网络错误。
用 curl 报错：
* http2 error: Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.

**Comment by josh-chan** [comment]
另外，分流后, go 的 request.TLS 也没了

**Comment by liberal-boy** [comment]
请附上配置文件和日志
