### ISSUE TITLE
请问分流器该如何监听 IPv6 地址的端口呢？

### ISSUE THREAD

**Issue by hiikii** [liberal-boy/tls-shunt-proxy#29]
目前没有看到针对 IPv6 的有关配置说明，自己也尝试着配置了但是没有成功，只好来求助了。😶

**Comment by liberal-boy** [comment]
没有成功的表现是什么，是怎么配置的

**Comment by hiikii** [comment]
@liberal-boy 是这样子的，因为我的服务器 IPv4 和 IPv6 地址都有，我想尝试让两边都可以正常工作，所以我试着修改配置文件并使用命令看看是否会报错，结果我修改的配置并不能正常通过，所以才有了此疑问。下面是我尝试的一些修改，如果是我理解的不对，还望指教：

1. 不填写地址，直接写 `listen: 443`
报错：failed to listen on 443: listen tcp: address 443: missing port in address

2. 换了一种方式再次测试：`listen: [::]:443`
报错：failed to read config /etc/tls-shunt-proxy/config.yaml: yaml: line 1: did not find expected node content

我想了一下，可能我需要将实际的 IPv6 地址也给加进去？另外再问一个问题，我可以在配置里写监听多个端口吗？

**Comment by liberal-boy** [comment]
> @liberal-boy 是这样子的，因为我的服务器 IPv4 和 IPv6 地址都有，我想尝试让两边都可以正常工作，所以我试着修改配置文件并使用命令看看是否会报错，结果我修改的配置并不能正常通过，所以才有了此疑问。下面是我尝试的一些修改，如果是我理解的不对，还望指教：
> 
> 1. 不填写地址，直接写 `listen: 443`
>    报错：failed to listen on 443: listen tcp: address 443: missing port in address
> 2. 换了一种方式再次测试：`listen: [::]:443`
>    报错：failed to read config /etc/tls-shunt-proxy/config.yaml: yaml: line 1: did not find expected node content
> 
> 我想了一下，可能我需要将实际的 IPv6 地址也给加进去？另外再问一个问题，我可以在配置里写监听多个端口吗？

多个端口号不允许。0.0.0.0 就是 v4v6。

**Comment by hiikii** [comment]
非常感谢，看来只是我认知上出现了错误……
