### ISSUE TITLE
同时开了path和handler就是403

### ISSUE THREAD

**Issue by maryjeck** [liberal-boy/tls-shunt-proxy#5]

**Comment by liberal-boy** [comment]
需要 配置文件, log 等信息。

**Comment by maryjeck** [comment]
listen: 0.0.0.0:443

# vhosts: 按照按照 tls sni 扩展划分为多个虚拟 host
vhosts:

    # name 对应 tls sni 扩展的 server name
  - name: xxx.xxxx.xxx

    # tlsoffloading: 解开 tls，true 为解开，解开后可以识别 http 流量，适用于 vmess over tls 和 http over tls (https) 分流等
    tlsoffloading: true

    # managedcert: 管理证书，开启后将自动从 LetsEncrypt 获取证书，根据 LetsEncrypt 的要求，必须监听 443 端口才能签发
    # 开启时 cert 和 key 设置的证书无效，关闭时将使用 cert 和 key 设置的证书
    managedcert: true

    # alpn: ALPN, 多个 next protocol 之间用 "," 分隔
    alpn: h2,http/1.1

    # protocols: 指定 tls 协议版本，格式为 min,max , 可用值 tls12(默认最小), tls13(默认最大)
    # 如果最小值和最大值相同，那么你只需要写一次
    # tls12 仅支持 FS 且 AEAD 的加密套件
    protocols: tls13,tls13

    # http: 识别出的 http 流量的处理方式
    http:

      # paths: 按 http 请求的 path 分流，从上到下匹配，找不到匹配项则使用 http 的 handler
      paths:
          # path: path 以该字符串开头的请求将应用此 handler
        - path: /Cfluxay/
          handler: proxyPass
          args: 127.0.0.1:12518

      # handler: fileServer 将服务一个静态网站
      # fileServer 支持 h2c, 如果使用 fileServer 处理 http, 且未设置 paths, alpn 可以开启 h2
      handler: fileServer
      # args: 静态网站的文件路径
      args: /root/caddy/www

    # default: 其他流量处理方式
    default:
      # handler: proxyPass 将流量转发至另一个地址
      handler: proxyPass

      # args: 转发的目标地址
      args: 127.0.0.1:12519

      # args: 也可以使用 domain socket
      # args: unix:/path/to/ds/file

**Comment by maryjeck** [comment]
找到原因了，tls-shunt-proxy权限问题。
将/etc/systemd/system/tls-shunt-proxy.service中的User注释掉，开放其root权限，如下。
`[Service]
Type=simple

#User=tls-shunt-proxy

AmbientCapabilities=CAP_NET_BIND_SERVICE

StandardError=journal

WorkingDirectory=/etc/ssl/tls-shunt-proxy

ExecStart=/usr/local/bin/tls-shunt-proxy -config /etc/tls-shunt-proxy/config.yaml
`

**Comment by liberal-boy** [comment]
@maryjeck 不建议用root权限运行，你应该设置web目录的权限。
