### ISSUE TITLE
分流 VMess 性能 

### ISSUE THREAD

**Issue by phlinhng** [liberal-boy/tls-shunt-proxy#7]
@CyangHH @ phlinhng/v2ray-tcp-tls-web#13
> 在跑speedtest,tls-shunt-proxy比较影响性能

**Comment by liberal-boy** [comment]
请提供“影响性能”的表现，测试方法和环境。

**Comment by CyangHH** [comment]
抱歉，我没办法提供严谨的测试结论，目前只是基于同一个VPS不同脚本的speedtest测速结果。
采用nginx+v2ray大概能跑30MB+；采用coddy+tls-shunt-proxy+v2ray跑到20MB+，使用TOP命令看CPU占用已经到100%，其中tls-shunt-proxy占用50%+

**Comment by liberal-boy** [comment]
@CyangHH tls-shunt-proxy的cpu消耗主要来自tls，go的tls实现效率是不如openssl的，这个无解，另外使用tls-shunt-proxy后为什么还要经过caddy？

**Comment by phlinhng** [comment]
> 抱歉，我没办法提供严谨的测试结论，目前只是基于同一个VPS不同脚本的speedtest测速结果。
> 采用nginx+v2ray大概能跑30MB+；采用coddy+tls-shunt-proxy+v2ray跑到20MB+，使用TOP命令看CPU占用已经到100%，其中tls-shunt-proxy占用50%+

如果你說的 coddy+tls-shunt-proxy+v2ray 是指我的腳本，那麼 v2ray 和 caddy 沒有關係，我的腳本裡的的 caddy 只是用來做 80 到 443 的重定向。v2ray 流量會從 443 直接經過分流器，不會通過 caddy。

**Comment by CyangHH** [comment]
@liberal-boy @phlinhng  感谢各位 Close吧
