### ISSUE TITLE
LE簽發的證書爲什麼會出現如下錯誤？

### ISSUE THREAD

**Issue by forevoliu** [liberal-boy/tls-shunt-proxy#8]
failed to proxy pass: remote error: tls: bad certificate

    # cert: tls 证书路径，
    cert: /etc/ssl/***********.crt

    # key: tls 私钥路径
    key: /etc/ssl/private.key

**Comment by liberal-boy** [comment]
请确认证书是否可信，是否在有效期内，是否与域名对应。
