### ISSUE TITLE
希望增加 ws path 分流传送客户端 IP 给后端的功能 

### ISSUE THREAD

**Issue by phlinhng** [liberal-boy/tls-shunt-proxy#9]
透过 X-Forwarded-For 传送客户端 IP 给后端，方便 v2ray 统计。

**Comment by liberal-boy** [comment]
暂无此计划，本项目旨在简单便于搭建，这类用户同常不需要获取客户端 ip，高级需求应使用 haproxy 等更专业的工具。

**Comment by liberal-boy** [comment]
此项目是工作在4层的，实现http的功能恐降低效率，下一步可以考虑支持使用 proxy protocol 向后端传递源地址。

**Comment by liberal-boy** [comment]
cf2f7b5
